server:
  port: 8761
  wait-time-in-ms-when-sync-empty: 2000

eureka: 
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
       

      
       